apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/instance: metrics-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: jobset
  name: jobset-metrics-cert
  namespace: openshift-jobset-operator
spec:
  commonName: jobset-metrics
  dnsNames:
  - $(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc
  - $(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc.cluster.local
  duration: 8760h
  issuerRef:
    kind: Issuer
    name: jobset-selfsigned-issuer
  renewBefore: 720h
  secretName: metrics-server-cert
  usages:
  - server auth
  - client auth
