apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/part-of: jobset
    control-plane: controller-manager
  name: jobset-controller-manager-metrics-monitor
  namespace: openshift-jobset-operator
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: ca.crt
          name: metrics-server-cert
      cert:
        secret:
          key: tls.crt
          name: ${METRICS_PROMETHEUS_CLIENT_CERT_SECRET_NAME}
      insecureSkipVerify: false
      keySecret:
        key: tls.key
        name: ${METRICS_PROMETHEUS_CLIENT_CERT_SECRET_NAME}
      serverName: ${METRICS_SERVICE_NAME}.${METRICS_SERVICE_NAMESPACE}.svc
  selector:
    matchLabels:
      control-plane: controller-manager
