apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobset-prometheus-k8s
  namespace: openshift-jobset-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobset-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
