kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobset-operator
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - jobsetoperators
      - jobsetoperators/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
      - watch
