kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobset-operator
  namespace: openshift-jobset-operator
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - events
      - pods
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - list
      - create
      - update
