kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobset-operand
subjects:
- kind: ServiceAccount
  name: jobset-operator
  namespace: openshift-jobset-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobset-operand
